version: '3.0'

services:
  db:
    image: postgres:9.6
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  webapp:
    build: webapp
    depends_on:
      - db
    ports:
      - 3000:3000
